use sakila;
-- List the number of films per category.
select category.name, category_id, count(*) 
from film_category 
inner join category 
	using (category_id)
	group by category_id,category.name;
    
    SELECT 
    category.*,
    COUNT(film_category.film_id) AS film_count
FROM 
    film_category
INNER JOIN 
    category USING (category_id)
GROUP BY 
    category.category_id;

-- Retrieve the store ID, city, and country for each store
select store_id, address_id, city, country
from store
inner join address      
using (address_id)
inner join city
using (city_id) 
inner join country
on city.country_id = country.country_id;

-- Calculate the total revenue generated by each store in dollars.
select store_id, sum(amount) as Somme
from payment
inner join customer
using (customer_id)
inner join store
using (store_id)
group by store_id;

-- Determine the average running time of films for each category.
select name, avg(length) from film
inner join film_category
using (film_id)
inner join category
using (category_id)
group by name;
